### ISSUE TITLE
Feature request: Digest auth

### ISSUE THREAD

**Issue by shikasta-net** [phpbg/easysync#16]
My self-hosted WebDAV all use Digest auth to separate different areas.  I might have missed it but I think Digest auth isn't supported yet.  Hopefully not too hard to add alongside Basic.

**Comment by phpbg** [comment]
Hi, indeed digest is missing.

I just need to figure out if I can auto detect the auth method (i want to avoid asking the user wether it is basic auth or digest).

Can you tell which server you use?

**Comment by shikasta-net** [comment]
Thanks :smile: 
I just use Apache based on docker httpd image.  I set the following config and pass in the realm (AuthName) as an environment variable to the startup script.  I run a couple of these for different purposes behind a reverse proxy; the mounted `user.passwd` contains everyone, with different realms.  Bit of a simple hack but it's fast and as far as I can tell, secure.
```
DavLockDB "/var/lib/dav/DavLock"
Alias / "/var/lib/dav/data/"
<Directory "/var/lib/dav/data/">
  Dav On
  Options Indexes

  AuthType Digest
  AuthName "{{ realm }}"
  AuthUserFile "/user.passwd"
  Require valid-user
</Directory>
```
[Apache sets the `www-authenticate` based on the auth type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate#syntax).  It would require two requests to the server; the first (401) will give you that header with either "Digest" or "Basic" at the start (or something else, possibly).  It should then be just a case of bundling the credentials slightly differently in the auth header.

**Comment by phpbg** [comment]
Digest auth is availaible in v1.5 (available within a few hours on playstore)
