### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by sunjam** [phpbg/easysync#2]
I want to encourage you to add a donation option within the app, even if it is simply a link to your paypal or similar.
Or, I really like what Cryptomator does in offering a paid donation, which unlocks Dark Mode via a text key emailed to the donor.

Thanks for considering!  I hope this idea is of interest, especially if you consider offering this outside the Google Play store.

**Comment by phpbg** [comment]
Thank you for your interest, I added a [donation link](https://github.com/sponsors/phpbg).

FDroid release will also come soon...
