### ISSUE TITLE
Option to specify which mobile folder to sync

### ISSUE THREAD

**Issue by dbrand666** [phpbg/easysync#3]
It looks like EasySync is currently syncing (or trying to sync) the entire "Internal shared storage" on the phone to the DAV folder you specify. Some might prefer to have more control over which folders are synced.

**Comment by phpbg** [comment]
Thanks for your feedback.

Indeed the `easy` part of `easysync` is that you do not have to configure folders. The whole "user" files are synced (ie media files and downloaded files).

There are already existing sync app where you can setup per folder sync.

I am looking for the simplest user experience possible.
* Choosing folders looks complicated (but you may suggest your ux flow)
* maybe toogles such as `Synchronize pictures`, `Synchronize downloads`, `Synchronize audio` would be simpler/enough

What do you think? Let's collect more feedback.

**Comment by Surendrajat** [comment]
I know it'll be not so _easy_ but I really like how
[Autosync](https://play.google.com/store/apps/details?id=com.ttxapps.autosync&hl=en&gl=US) does it.

**Comment by needthisforctf** [comment]
@phpbg, I think toggles you mentioned are a good way to approach this, but additionally you can:

- add an «advanced» toggle that lets you add the folder by entering the full path. This way you avoid making folder selection UX while still keeping the ability to add folders
- another way would be to add a toggle for /storage/Sync folder. Usually, I don't want to sync anything and everything (especially Downloads folder) to Nextcloud, I just want to sync a specific folder there that has all the stuff I need
- also, users of Nextcloud are usually tech-savvy enough to not be bothered by folder selection UX, so I'd say go with it, this is the most versatile option so far

The current form of the app that syncs anything and everything will just turn my Nextcloud into a dumpster fire, so as much as I want to try the easysync out, I can't while this issue is there. Thanks for doing the crucial work to address #19 instead of Nextcloud team, keep it going!

**Comment by bohwaz** [comment]
Yes, it seems like a great app, but our WebDAV root is shared between users, so we don't want to share all of our phone data, just a few work directories from WebDAV :)

For example I want to be able to sync the "accounting" folder but not the "user messages" folder, and be able to choose where it is synced on the phone storage.

**Comment by phpbg** [comment]
I think adding toggles `Synchronize pictures`, `Synchronize downloads`, `Synchronize audio` would address most of your uses cases while keeping simplicity.

But I don't know what would happen to already synchronized files if you change the toggle. For example say you enabled all toggles, started sync, then disable syncing downloads...

**Comment by bohwaz** [comment]
I would expect files to be left as they are, on both sides.

But it wouldn't be enough: for example I want to synchronize my audiobooks, but not my music library, I want to sync my photos but not my screenshots, etc.

**Comment by citizenserious** [comment]
I would like to synchronize my backups from NeoBackup and Signal (:

**Comment by phpbg** [comment]
> I would like to synchronize my backups from NeoBackup and Signal (:

Just store your `Signal` backup in a synced folder, say `Downloads/Signal`, and it will be synced.

If NeoBackup allows to select any folder then it should also work.

**Comment by needthisforctf** [comment]
> Just store your `Signal` backup in a synced folder, say `Download/Signal`, and it will be synced.

Not every program works with this approach, some have hard-coded backup paths. Also, since now we have granual file access in Android, I don't really want to save my backups or other precious stuff in /Downloads where every app can see it.

**Comment by OmlineEditor** [comment]
you need to make a more convenient way to select a folder for synchronization, now you can only specify the path there with your hands. it is not convenient, you need to make a folder selection through a convenient menu.

**Comment by phpbg** [comment]
> you need to make a more convenient way to select a folder for synchronization, now you can only specify the path there with your hands. it is not convenient, you need to make a folder selection through a convenient menu.

I agree on this, but that's a different feature request. This specific issue is about selecting which folder are synced (instead of syncing everything)

**Comment by citizenserious** [comment]
Maybe it could be possible to make such a feature optional for "advanced users" so the idea of easysync could stay the same (;

**Comment by OmlineEditor** [comment]
advanced functions need to be added here, without them it is impossible to conveniently and fully use the program

**Comment by h0m3** [comment]
> Thanks for your feedback.
> 
> Indeed the `easy` part of `easysync` is that you do not have to configure folders. The whole "user" files are synced (ie media files and downloaded files).
> 
> There are already existing sync app where you can setup per folder sync.
> 
> I am looking for the simplest user experience possible.
> 
>     * Choosing folders looks complicated (but you may suggest your ux flow)
> 
>     * maybe toogles such as `Synchronize pictures`, `Synchronize downloads`, `Synchronize audio` would be simpler/enough
> 
> 
> What do you think? Let's collect more feedback.

I dont want to sound like an asshole by asking this here but I've searched a lot and didn't find anything. Do you know another Open Source sync app that supports WebDAV? I really need to specify which folder I want to sync because of stuff like WhatsApp.

**Comment by phpbg** [comment]
> Do you know another Open Source sync app that supports WebDAV? I really need to specify which folder I want to sync because of stuff like WhatsApp.

I don't know any which is open source.

You can configure WhatsApp to keep media files private and not put them in your gallery (if that's what you want)...

**Comment by bohwaz** [comment]
Same, there is no open source WebDAV sync tool on Android, and allowing to select what we want to sync would make this app more useful, but if not, maybe we should consider a fork?

**Comment by phpbg** [comment]
Why would you fork? If you are willing to contribute just send a pull request.

Right now I think the most simple and easy to implement would be to have an option to exclude folders. By default, everything will be synced, unless you explicitely exclude some folders.

For example, you could exclude the whole downloads folder, or the whatsapp images folder.

What do you think?

**Comment by bohwaz** [comment]
Sorry I understood that you were opposed to including this feature in EasySync.

Exluding: that's a good idea, but I don't think that's enough. If you want to only sync one folder, manually excluding everything else by checking other folders sounds cumbersome.

**Comment by bohwaz** [comment]
Also, my usage would be to sync a work-related folder, so none of my personal phone directories should be synced.

**Comment by phpbg** [comment]
Work is ongoing:
![image](https://github.com/phpbg/easysync/assets/43315561/bd695557-7592-4345-a80d-d80940a598e5)

**Comment by OmlineEditor** [comment]
> Work is ongoing:


is it possible to specify other folder paths in this list? I want to point out the right path for me myself

**Comment by phpbg** [comment]
> is it possible to specify other folder paths in this list? I want to point out the right path for me myself

No, it will show you the whole list of synchronizable folders, and you will just have to toggle it on or off.
I'll try to also show remote folders too.

**Comment by phpbg** [comment]
Hi all, a new release is published as beta testing in playstore.
Feel free to try it and report back.
I will also publish it on the free version today

**Comment by phpbg** [comment]
Released with 1.12
