### ISSUE TITLE
Not all files synchronized, stuck at 50%

### ISSUE THREAD

**Issue by LM1LC3N7** [phpbg/easysync#32]
**Describe the bug**
I setup the app between multiple user profile in Android. Nextcloud is used to host and allow sync between all these profiles. 
From the first profile, I configured the app to send multiple folders (Documents, Ringstones). On the second profile, I want to first download files from nextcloud as they don't exist on the internal memory, and then send any new files to nextcloud again. So basically, two way sync tasks.
But on the second profile,  even by manually starting a sync task, I never reach the 100% and never get my remote files to be downloaded.

![IMG_20240324_223835](https://github.com/phpbg/easysync/assets/14235706/d21db6b9-af16-4d62-b407-4e9bb03d0399)

**Smartphone (please complete the following information):**
 - Device brand/model: Google Pixel 8 Pro
 - Android version: Android 14 (grapheneOS)
 - Restrictions: yes, the app has "storage scope" (it can only see folders I explicitly give access)

**Comment by LM1LC3N7** [comment]
I read again the readme and all folder in want to sync are on the list:
- Documents
- Ringstones
- Recordings

Only one is missing (not supported): .seebackup

**Comment by phpbg** [comment]
Hi, can you manage to get some logs with `adb logcat`?

**Comment by vkamydo** [comment]
I was seeing same behavior, and in adb logcat there were sync errors from the WebDAV server (http 413 in my case). To fix that I had to increase client_max_body_size option in nginx. Would be nice if the app could show an error somewhere in the UI when that happens.

**Comment by phpbg** [comment]
> I was seeing same behavior, and in adb logcat there were sync errors from the WebDAV server (http 413 in my case). To fix that I had to increase client_max_body_size option in nginx. Would be nice if the app could show an error somewhere in the UI when that happens.

Thanks for your feedback, good idea. I'll implement a notification on server failures

**Comment by LM1LC3N7** [comment]
Thanks @vkamydo and sorry @phpbg I was not able to gather logs.

**Comment by phpbg** [comment]
Fix released in coming v1.9
