### ISSUE TITLE
text could not be parsed

### ISSUE THREAD

**Issue by moeraccoon** [phpbg/easysync#36]
**Describe the bug**
Upon filling in the required things during setup (url, username, password and remote path) a text that says 
"Error: Text 'Thu, 06 Jun 2024 19:45:34 GMT' could not be parsed at index 0"
appears, I copied as it was on the screen at the moment, then tried to save again a while after but the time remained the same so I don't think it just shows the current time.

**Smartphone (please complete the following information):**
 - Device brand/model: Google pixel 6a
 - Android version: Version 14, specifically I'm using graphene OS

**Comment by phpbg** [comment]
This is probably an arror while parsing your webdav server's response.

What is your webdav server?

**Comment by moeraccoon** [comment]
> What is your webdav server?

I'm using mailbox.org which has cloud among it's services.
I doubt this is helpful, sorry but I'm pretty ignorant, but on linux I could connect fine with no errors.

Thank you for your help.

**Comment by moeraccoon** [comment]
Update, I tried again today and the error is still there but the date changed quite a bit, it now says Tue 25 Apr 2023 5.52.06 GMT

**Comment by phpbg** [comment]
There's something wrong when parsing your provider timestamps.
It needs a bugfix.
I'll create an account to reproduce and fix it.
Be patient, I'll report back.

**Comment by phpbg** [comment]
Hi, the fix will be included in next version. It generally takes a few days to be published.

Beware that support is basic:
* it does not preserve file creation timestamps,
* use `https://office.mailbox.org/servlet/webdav.infostore` as url 
* and `/Userstore/<firstname lastname>/` as remote folder (or any subfolder such as `/Userstore/<firstname lastname>/Documents`)
