### ISSUE TITLE
Error: unterminated entity ref

### ISSUE THREAD

**Issue by DevEnt-LNT** [phpbg/easysync#38]
Hi,
While trying to save the DAV settings I receive the following error:

-Error: unterminated entity ref (position:TEXT@44:84 in okhttp3.ResponseBody$BomAwareReader@d2a1687)

URL: https:// WebDAV-link to Nextcloud
Username: Loginname
Password: Nextcloud valid App-PW
Remote DAV path to sync: /

Device: Google Pixel 7A
Android: 14

Thanks,
Andy
![EasySync](https://github.com/user-attachments/assets/1989efd8-b1b4-4a35-bc39-b5e83ed3b651)

**Comment by phpbg** [comment]
Hi,
- can you create an empty folder on your nextcloud instance, say `test`, and configure `Remote DAV path to sync` to `/test` ? this will tell wether there is something wrong with your nextcloud instance, or with the contents of your current root folder.
- Then, can you check the list of files and folders at the root of your nextcloud user files? Is there any filename (or folder name) that contains weird non utf8 character?

Anyway thanks for your support!
Regards

**Comment by DevEnt-LNT** [comment]
Hi,

- trying to save settings with suggested settings (for folder /test) results in same error but with ....@c6b241e at the end
- no weird utf8 character contained in any entries

Thanks,
Andy

**Comment by phpbg** [comment]
It seems the app fails to parse your server's response.

Could you try to make the request with curl and paste the result?

Change user:pass with your own user/password, and change the url too.

curl -u user:pass -X PROPFIND -H 'Depth: 1' https://example.com

**Comment by DevEnt-LNT** [comment]
Hi,
We were able to find the issue. Was related to our Proxy-Server an the implementation we have for Nextcloud.
Thanks a lot for your help and keep on the good work, and maybe on some of the enhancements ;-)
