### ISSUE TITLE
Syncronization is incomplete

### ISSUE THREAD

**Issue by dbrand666** [phpbg/easysync#4]
It looks like most of my phone isn't getting synced to DAV. It's probably because of permissions. Is it possible to grant EasySync permission to access all files on internal storage? Would root be required?

**Comment by phpbg** [comment]
* Root is not required.
* When you start the app, it will show you a warning if you did not grant permissions.
* What's your version of android? And phone model?

**Comment by dbrand666** [comment]
I'm running the latest Android 14 on a Pixel 7. I granted all the permissions it asked for. The sync got to 100%, I didn't see any errors. I even went in and renamed a file that was synced and it was resynced.
Would it help if I collected a list of which folders were backed up vs skipped? Eg. In Android, media was backed up but data and obb were skipped.
I uninstalled the app for now but I'd be happy to reinstall and try again. Is there a way to generate a log?

**Comment by phpbg** [comment]
Thanks for your feedback.

That's the way it is intended to work: only media and downloads are synced.

This app is not a backup app, it synchronizes "regular" user files, ie media and downloads, but not internal android data/obb files.

**Comment by phpbg** [comment]
Documentation was updated to reflect precisely what is synced or not: https://github.com/phpbg/easysync#what-is-synchronized

Feel free to comment if it is not clear enough.

**Comment by be1** [comment]
Hello,
AIFF (.aif or .aiff) audio files seems not synchronized.
