### ISSUE TITLE
add support SMB

### ISSUE THREAD

**Issue by OmlineEditor** [phpbg/easysync#7]
please add another protocol for support. SMB is the more popular protocol on the LAN and it will be the best solution for the home.

**Comment by phpbg** [comment]
Hi,

SMB is a quite different protocol, so "adding" it is not that easy.

It seems there are already SMB sync apps existing, so that will not be a priority right now...

**Comment by OmlineEditor** [comment]
Well, it's not a priority. Just add it to the list of desired tasks. If you know good and stable programs for synchronization over the SMB protocol, then recommend it to me.

**Comment by stokito** [comment]
The EasySync advantage is that it's small and focused on the WebDAV. If you wish SMB then try the Round-Sync (fork of RCX) which is basically RClone packed as an app.
You can download a beta version from here
https://github.com/newhinton/Round-Sync/releases/tag/v2.2.2

**Comment by essys** [comment]
SMBSync2 works like a charm:
https://github.com/Sentaroh/SMBSync2

**Comment by phpbg** [comment]
There is no plan to support other protocols than webdav yet.
