### ISSUE TITLE
NextCloud app

### ISSUE THREAD

**Issue by stokito** [phpbg/easysync#9]
At some point of time users may ask you for a basic view files functionality. Now there are only proprietary programs for this.
I asked NextCloud team if they can suppot just a plain WebDAV + Basic Auth and they said that this is out of scope but actually possible
https://github.com/nextcloud/android/issues/11639

Maybe you can make this happen? Or someone who read this.
This is probably a low prio because proprietary programs can solve most of problems today.

**Comment by dbrand666** [comment]
Round Sync is Free Software that lets you browse a webdav server much like the files app does for local files. Is that what you're looking for?

It's available on f-droid.

**Comment by stokito** [comment]
yes, I do use it now alongside of the EasySync. I don't like that it's too big because internally it contains entire RClone which is written in Golang. The EasySink is much simpler and lightweight.
The file browsing and managing is very basic in the RoundSync.
Here I'm more talking aboud GDrive / Dropbox experience. Where a user can even edit or play files.

**Comment by dbrand666** [comment]
It supports SAF so you should be able to use your preferred file explorer if you don't like its UI - I use Material Files. I'm not sure what you mean by it not supporting editing or playing. Both seem to work for me.

What doesn't work as far as I can tell is offline access and syncing. There may be a way to do something like it by layering cache on to of the webdav but I couldn't figure it out the time I tried it.

You're right that it's much more complex than Easysync.

**Comment by phpbg** [comment]
Right now there is no file browsing, because EasySync works in background and sync all files with your phone.

As all files are synced, you can simply browse/open/edit them using any file app on your phone.

For this reason adding file browsing does not seem necessary (unless you want to access WebDAV files outside your phone scope)...

**Comment by stokito** [comment]
thank you for the response.

**Comment by stokito** [comment]
@dbrand666  I'm not familiar with the SAF but found a separate project for WebDAV SAF https://github.com/alexbakker/webdav-provider

Will try it later, thank you for pointing.

Still I wish to have some functionality like folder sharing e.g. to share photos with family. This is significantly out of scope because here we need user management and but just to get the whole idea of what is needed. Backup and syncing only one usage level, browse directory, playing videos and viewing photos is another and sharing with others or even publicly is more advanced level.

**Comment by dbrand666** [comment]
Round Sync supports SAF itself but I'll take a look at WebDAV SAF too.
Sharing would be a server function not client. Nextcloud supports shared folders in a few different ways. Group folders, eg.
